import { useState, useEffect, useMemo, Fragment } from 'react'
import { DS } from '../data'
import { getFields } from '../models'
import { useUI, badgeClass } from '../context/UIContext'
import { useSearch } from '../context/SearchContext'
import { StatsCards } from '../components/StatsCards'
import { SearchBar } from '../components/SearchBar'
import { EmptyState } from '../components/EmptyState'

export function RequirementsView() {
  const [data, setData] = useState<any[]>([]); const [expanded, setExpanded] = useState<Set<string>>(new Set()); const [key, setKey] = useState(0); const reload = () => setKey(k => k + 1); const { showToast, showModal } = useUI()
  useEffect(() => { setData(DS.getAll('pm_requirement')) }, [key])
  const capabilities = useMemo(() => DS.getAll('pm_capability'), [key]); const projects = useMemo(() => DS.getAll('pm_project'), [key]); const products = useMemo(() => DS.getAll('pm_product'), [key]); const epics = useMemo(() => DS.getAll('pm_epic'), [key]); const assignments = useMemo(() => DS.getAll('pm_assignment'), [key])
  const toggle = (id: string) => { setExpanded(prev => { const s = new Set(prev); if (s.has(id)) s.delete(id); else s.add(id); return s }) }
  const openEditReq = (id: string) => { const rec = DS.getById('pm_requirement', id); const rsConfigs = DS.query('pm_config', { pm_type: 'requirement_status' }); const psConfigs = DS.query('pm_config', { pm_type: 'psc_approval_status' }); showModal({ title: 'Edit Requirement', fields: getFields('pm_requirement').filter(f => !['pm_capabilityid', 'pm_projectname', 'pm_status', 'pm_pscapprovalstatus'].includes(f.name)), data: rec, extraContent: (<div><label>Capability</label><select id="reqCapability" data-extra defaultValue={rec.pm_capabilityid || ''}><option value="">None</option>{capabilities.map((c: any) => <option key={c.id} value={c.id}>{c.pm_name}</option>)}</select><label>Status</label><select id="reqStatus" data-extra defaultValue={rec.pm_status || ''}><option value="">None</option>{rsConfigs.map((c: any) => <option key={c.id} value={c.pm_name}>{c.pm_name}</option>)}</select><label>PSC Approval Status</label><select id="reqPSC" data-extra defaultValue={rec.pm_pscapprovalstatus || ''}><option value="">None</option>{psConfigs.map((c: any) => <option key={c.id} value={c.pm_name}>{c.pm_name}</option>)}</select><label>Project</label><select id="reqProject" data-extra defaultValue={rec.pm_projectname || ''}><option value="">None</option>{projects.map((p: any) => <option key={p.id} value={p.id}>{p.pm_name}</option>)}</select></div>), onSave: (fd) => { fd.pm_capabilityid = (document.getElementById('reqCapability') as HTMLSelectElement)?.value || ''; fd.pm_status = (document.getElementById('reqStatus') as HTMLSelectElement)?.value || ''; fd.pm_pscapprovalstatus = (document.getElementById('reqPSC') as HTMLSelectElement)?.value || ''; fd.pm_projectname = (document.getElementById('reqProject') as HTMLSelectElement)?.value || ''; DS.update('pm_requirement', id, fd); reload(); showToast('Requirement updated!') }, onDelete: () => { DS.delete('pm_requirement', id); reload(); showToast('Requirement deleted!') } }) }
  const { term } = useSearch(); const filtered = term ? data.filter((r: any) => Object.values(r).some(v => String(v ?? '').toLowerCase().includes(term.toLowerCase()))) : data
  return (
    <div>
      <div className="dashboard-header"><h2>📋 Requirement Dashboard</h2><button className="btn btn-primary" onClick={() => { const rsConfigs = DS.query('pm_config', { pm_type: 'requirement_status' }); const psConfigs = DS.query('pm_config', { pm_type: 'psc_approval_status' }); showModal({ title: 'New Requirement', fields: getFields('pm_requirement').filter(f => !['pm_capabilityid', 'pm_projectname', 'pm_status', 'pm_pscapprovalstatus'].includes(f.name)), extraContent: (<div><label>Capability</label><select id="reqCapability" data-extra><option value="">Select Capability...</option>{capabilities.map((c: any) => <option key={c.id} value={c.id}>{c.pm_name}</option>)}</select><label>Status</label><select id="reqStatus" data-extra><option value="">None</option>{rsConfigs.map((c: any) => <option key={c.id} value={c.pm_name}>{c.pm_name}</option>)}</select><label>PSC Approval Status</label><select id="reqPSC" data-extra><option value="">None</option>{psConfigs.map((c: any) => <option key={c.id} value={c.pm_name}>{c.pm_name}</option>)}</select><label>Project</label><select id="reqProject" data-extra><option value="">None</option>{projects.map((p: any) => <option key={p.id} value={p.id}>{p.pm_name}</option>)}</select></div>), onSave: (fd) => { fd.pm_capabilityid = (document.getElementById('reqCapability') as HTMLSelectElement).value; fd.pm_status = (document.getElementById('reqStatus') as HTMLSelectElement).value; fd.pm_pscapprovalstatus = (document.getElementById('reqPSC') as HTMLSelectElement).value; fd.pm_projectname = (document.getElementById('reqProject') as HTMLSelectElement).value; DS.create('pm_requirement', fd); reload(); showToast('Requirement created!') } }) }}>+ New Requirement</button></div>
      <StatsCards stats={[{ value: data.length, label: 'Requirements' },{ value: data.filter((r: any) => r.pm_status === 'Linked').length, label: 'Linked' },{ value: data.filter((r: any) => r.pm_pscapprovalrequired === 'Yes').length, label: 'Need PSC' },{ value: data.filter((r: any) => r.pm_pscapprovalstatus === 'Approved').length, label: 'PSC Approved' }]} />
      <SearchBar />
      {!filtered.length ? <EmptyState msg="No requirements found" /> : (
        <table className="data-table"><thead><tr><th>Detail</th><th>Project</th><th>Product</th><th>Effort</th><th>Status</th><th>PSC Approval</th><th>Actions</th></tr></thead>
        <tbody>{filtered.map((req: any) => { const proj = projects.find((p: any) => p.id === req.pm_projectname); const prod = proj ? products.find((p: any) => p.id === proj.pm_productname) : null; const reqEpics = req.pm_projectname ? epics.filter((e: any) => e.pm_projectname === req.pm_projectname) : []; const isExp = expanded.has(req.id); return (
        <Fragment key={req.id}>
        <tr className={`data-row${isExp ? ' project-row-expanded' : ''} project-main-row`} onClick={() => toggle(req.id)} style={{ cursor: 'pointer' }}><td>{req.pm_detail}</td><td>{proj?.pm_name || '—'}</td><td>{prod?.pm_name || '—'}</td><td><span style={{ fontWeight: 600 }}>{req.pm_effort || '—'}d</span></td><td><span className={`badge ${badgeClass(req.pm_status)}`}>{req.pm_status}</span></td><td>{req.pm_pscapprovalrequired === 'Yes' ? <span className={`badge ${badgeClass(req.pm_pscapprovalstatus)}`}>{req.pm_pscapprovalstatus}</span> : <span className="badge badge-gray">N/A</span>}</td><td className="actions-cell" onClick={e => e.stopPropagation()}><button className="btn-sm btn-edit" onClick={() => openEditReq(req.id)}>✏️ Edit</button><button className="btn-sm btn-delete" onClick={() => { if (confirm('Delete this requirement?')) { DS.delete('pm_requirement', req.id); reload(); showToast('Requirement deleted!') } }}>🗑️</button></td></tr>
        {isExp && reqEpics.length > 0 && reqEpics.map((e: any) => { const rag = e.pm_ragstatus === 'G' ? 'badge-green' : e.pm_ragstatus === 'A' ? 'badge-amber' : 'badge-red'; const epicAssigns = assignments.filter((a: any) => a.pm_epic === e.id); const devNames = epicAssigns.map((a: any) => DS.getResourceName(a.pm_resource)).join(', ') || '—'; return (<tr key={e.id} className="project-epic-row"><td colSpan={7}><div className="project-epic-item"><span className={`badge ${rag}`}>{e.pm_ragstatus || '—'}</span><span className="project-epic-name">{e.pm_title}</span><span className="project-epic-meta">Est: {e.pm_estimatedeffort || '—'}d | {e.pm_startdate || '?'} → {e.pm_releasedate || '?'}</span><span className="project-epic-devs">{devNames}</span></div></td></tr>) })}
        {isExp && reqEpics.length === 0 && <tr className="project-epic-row"><td colSpan={7} style={{ padding: '10px 14px 10px 44px', color: 'var(--text-muted)', fontSize: '0.85rem' }}>No epics in this project</td></tr>}
        </Fragment>
        ) })}</tbody></table>
      )}
    </div>
  )
}

